application:
  subdomain: openreader
  background_task: true
  public_path:
    - /
  routes:
    - /=http://openreader-webui:3003/
services:
  openreader-webui:
    # upstream: ghcr.io/richardr1126/openreader-webui:1.2.1
    image: registry.lazycat.cloud/czyt/richardr1126/openreader-webui:84af30d79031b66e
    environment:
      - API_BASE=http://openai-edge-tts:5050/v1
    binds:
      - /lzcapp/var/docstore:/app/docstore

  openai-edge-tts:
    # travisvn/openai-edge-tts:latest
    image: registry.lazycat.cloud/czyt/travisvn/openai-edge-tts:f9152e6f818570e8
    environment:
      - API_KEY=lazycattts
      - PORT=5050
      - DEFAULT_VOICE=zh-CN-YunjianNeural
      - DEFAULT_RESPONSE_FORMAT=mp3
      - DEFAULT_SPEED=1.0
      - DEFAULT_LANGUAGE=zh-CN
      - REQUIRE_API_KEY=False
      - REMOVE_FILTER=False
      - EXPAND_API=True
      - DETAILED_ERROR_LOGGING=True
